version: "3.8"

volumes:
  pg_data:
  static:
  media:
  frontend_build:

services:
  postgres:
    image: postgres:13
    container_name: postgres
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  kittygram_backend:
    image: igruzdo/kittygram_backend:latest
    container_name: backend
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - static:/app/collected_static
      - media:/app/media

  kittygram_frontend:
    image: igruzdo/kittygram_frontend:latest
    container_name: frontend
    volumes:
      - frontend_build:/app/build/

  kittygram_gateway:
    image: igruzdo/kittygram_gateway:latest
    container_name: gateway
    volumes:
      - frontend_build:/usr/share/nginx/html/
      - static:/var/www/static
      - media:/var/www/media
    ports:
      - "80:80"
    depends_on:
      - kittygram_backend
      - kittygram_frontend
