name: Deploy Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check_pep8:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10.4]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run PEP8 check
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  build_and_push_images:
    runs-on: ubuntu-latest
    needs: check_pep8
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/kittygram_backend:latest ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/kittygram_backend:latest

      - name: Build and push frontend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/kittygram_frontend:latest ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/kittygram_frontend:latest

      - name: Build and push gateway image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/kittygram_gateway:latest ./nginx
          docker push ${{ secrets.DOCKER_USERNAME }}/kittygram_gateway:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_images
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          # Устанавливаем pip (если еще нет)
          sudo apt-get update && sudo apt-get install -y python3-pip
          # Устанавливаем AWS CLI через pip
          pip install awscli --upgrade
          # Проверяем установку
          aws --version

      - name: Get VM IP and SSH-KEY via AWS CLI
        id: get-vm-ip
        run: |
          aws configure set aws_access_key_id ${{ secrets.YC_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.YC_SECRET_KEY }}
          aws configure set default.region ru-central1

          aws --endpoint-url=https://storage.yandexcloud.net \
            s3 cp s3://my-kittygram-bucket/terraform.tfstate ./terraform.tfstate

          VM_IP=$(jq -r '.outputs.vm_ip.value' ./terraform.tfstate)
          SSH_PRIV_KEY=$(jq -r '.outputs.ssh_priv_key.value' ./terraform.tfstate)

          mkdir -p ~/.ssh
          ssh-keyscan $VM_IP >> ~/.ssh/known_hosts

          echo "vm_ip=$VM_IP" >> $GITHUB_OUTPUT
          echo "ssh_priv_key=$SSH_PRIV_KEY" >> $GITHUB_OUTPUT

      - name: Decode SSH key
        run: |
          echo "${{ steps.get-vm-ip.outputs.ssh_priv_key }}" | base64 --decode > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Verify SSH Keys
        run: |
          echo "=== Private Key ==="
          head -n 3 ~/.ssh/id_rsa

          echo "=== Key Fingerprint ==="
          ssh-keygen -lf ~/.ssh/id_rsa

          echo "=== Testing Connection ==="
          ssh -i ~/.ssh/id_rsa \
            -o StrictHostKeyChecking=no \
            ubuntu@${{ steps.get-vm-ip.outputs.vm_ip }} \
            "echo 'Connection successful!'"

      - name: Copy docker-compose.production.yml via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ steps.get-vm-ip.outputs.vm_ip }}
          username: ubuntu
          key: ${{ github.workspace }}/.ssh/id_rsa
          source: "docker-compose.production.yml"
          target: "kittygram/"

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ steps.get-vm-ip.outputs.vm_ip }}
          username: ubuntu
          key: ${{ github.workspace }}/.ssh/id_rsa
          script: |
            cd kittygram/
            sudo touch .env
            sudo chmod 777 .env
            echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" > .env
            echo "DEBUG=${{ secrets.DEBUG }}" >> .env
            echo "ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}" >> .env
            echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
            echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
            echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> .env
            echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> .env
            docker compose -f docker-compose.production.yml pull
            docker compose -f docker-compose.production.yml down
            docker compose -f docker-compose.production.yml build
            docker compose -f docker-compose.production.yml up -d
            docker compose -f docker-compose.production.yml exec kittygram_backend python manage.py migrate
            docker compose -f docker-compose.production.yml exec kittygram_backend python manage.py collectstatic --noinput
            docker compose -f docker-compose.production.yml exec kittygram_backend cp -r /app/collected_static/. /static/

  run_tests:
    runs-on: ubuntu-latest
    needs: deploy
    env:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install and run frontend tests
        working-directory: ./frontend
        run: |
          npm install
          npm run test

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run backend tests
        working-directory: ./
        run: pytest ./tests/

  telegram-notify:
    runs-on: ubuntu-latest
    needs: run_tests
    steps:
      - name: Notify in Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ✅ Деплой успешно выполнен!

            👤 Автор коммита: ${{ github.actor }}
            📝 Сообщение коммита: ${{ github.event.commits[0].message }}

            📦 Репозиторий: ${{ github.repository }}
            🔗 Ссылка на коммит: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
